SUPABASE_URL = "https://ragaxopcaaekxckuorhe.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZ2F4b3BjYWFla3hja3VvcmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3ODU1NjcsImV4cCI6MjA4MzM2MTU2N30.vc7MvoShW3S7T7yW3I71EaJzbeI-bP6JWMjcR3jQWag"
SUPABASE_SECRET_KEY = "sb_secret_lVbuNE9m5GWjCjl8ju46rg_NJBMyiXf"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_E22rYAr7jMoLxYbX4XJ5Uw_udkSdDJ3"